kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ include "bluesky-pds.fullname" . }}-pvc"
  labels:
    {{- include "bluesky-pds.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.pds.dataStorage.storageClass }}
  volumeName: "{{ include "bluesky-pds.fullname" . }}-pv"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.pds.dataStorage.size }}
