apiVersion: v1
kind: Secret
metadata:
  name: cls-k8s
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
data:
  {{ if (lookup "v1" "Secret"  .Release.Namespace  "cls-k8s") }}
  cluster_id: {{ index (lookup "v1" "Secret"  .Release.Namespace  "cls-k8s").data "cluster_id" }}
  {{ else if .Values.ClusterID }}
  cluster_id: {{ .Values.ClusterID | b64enc }}
  {{ else }}
  cluster_id: {{ randAlphaNum 8 | lower | b64enc }}
  {{ end }}

